const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    GET_SHOES_INFO: 'GET_SHOES_INFO',
    GET_SHOES_INFO_SUCESSFUL: 'GET_SHOES_INFO_SUCESSFUL',
    GET_SHOES_INFO_FAIL: 'GET_SHOES_INFO_FAIL'
})

export default actionTypes;